Repository camunda-community-hub/camunda-tasklist-client-java, pull requests merged in 2025-06, with the labels that each got.

#330 added priority field task
  extension/client-java/src/main/java/io/camunda/tasklist/dto/Task.java
Labels: backport release/8.7, backport release/8.6

#349 moved to 8.7.0 api spec
  extension/generated/pom.xml
  extension/generated/tasklist-8.7.0.json
Labels: backport release/8.7

#361 added names to pom
  example/bootstrapping-test/pom.xml
  example/pom.xml
  example/readme-snippets/pom.xml
  extension/client-java/pom.xml
  extension/generated/pom.xml
  extension/pom.xml
  extension/spring-boot-starter-camunda-tasklist/pom.xml
  pom.xml
Labels: backport release/8.7, backport release/8.6, backport release/8.5
